### ISSUE TITLE
how to install tarantool ?

### ISSUE THREAD

**Issue by cheng417723** [tarantool/tracing#3]
intall tarantool  in this  way  https://www.tarantool.io/en/download/os-installation/1.10/rhel-centos-6-7/  . but  run  tarantoolctl rocks install http 2.0.1  error, like this : 

Installing http://rocks.tarantool.org/http-2.0.1-1.rockspec

Error: Could not find header file for TARANTOOL
  No file tarantool/module.h in /usr/local/include
  No file tarantool/module.h in /usr/include
You may have to install TARANTOOL in your system and/or pass TARANTOOL_DIR or TARANTOOL_INCDIR to the luarocks command.
Example: luarocks install http TARANTOOL_DIR=/usr/local

**Comment by Totktonada** [comment]
Install tarantool-devel package. Header files are needed to compile/install some rock.

**Comment by cheng417723** [comment]
thanks,   tarantoolctl rocks install http 2.0.1   run successfully, but why without http client ?
like this:
 sudo tarantoolctl rocks install http 2.0.1-1
Installing http://rocks.tarantool.org/http-2.0.1-1.rockspec
Initialized empty Git repository in /tmp/luarocks_http-2.0.1-1-o33Ftn/http/.git/
remote: Enumerating objects: 168, done.
remote: Counting objects: 100% (168/168), done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 959 (delta 75), reused 128 (delta 61), pack-reused 791
Receiving objects: 100% (959/959), 297.61 KiB | 85 KiB/s, done.
Resolving deltas: 100% (561/561), done.
Note: checking out '2.0.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 1ee57f8... Merge pull request #91 from tarantool/fix-installation-paths
-- The C compiler identification is GNU 6.3.1
-- Check for working C compiler: /opt/rh/devtoolset-6/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-6/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found TARANTOOL: /usr/include (found version "1.10.4-32-g89eb735") 
-- Tarantool LUADIR is /mnt/homework/.rocks/share/tarantool/rocks/http/2.0.1-1/lua
-- Tarantool LIBDIR is /mnt/homework/.rocks/share/tarantool/rocks/http/2.0.1-1/lib
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    version


-- Build files have been written to: /tmp/luarocks_http-2.0.1-1-o33Ftn/http/build.luarocks
Scanning dependencies of target httpd
[ 50%] Building C object http/CMakeFiles/httpd.dir/lib.c.o
[100%] Linking C shared library lib.so
[100%] Built target httpd
[100%] Built target httpd
Install the project...
-- Install configuration: "Debug"
-- Installing: /mnt/homework/.rocks/share/tarantool/rocks/http/2.0.1-1/lua/http/VERSION.lua
-- Installing: /mnt/homework/.rocks/share/tarantool/rocks/http/2.0.1-1/lib/http/lib.so
-- Installing: /mnt/homework/.rocks/share/tarantool/rocks/http/2.0.1-1/lua/http/server/init.lua
-- Installing: /mnt/homework/.rocks/share/tarantool/rocks/http/2.0.1-1/lua/http/server/tsgi_adapter.lua
-- Installing: /mnt/homework/.rocks/share/tarantool/rocks/http/2.0.1-1/lua/http/nginx_server/init.lua
-- Installing: /mnt/homework/.rocks/share/tarantool/rocks/http/2.0.1-1/lua/http/router/init.lua
-- Installing: /mnt/homework/.rocks/share/tarantool/rocks/http/2.0.1-1/lua/http/router/fs.lua
-- Installing: /mnt/homework/.rocks/share/tarantool/rocks/http/2.0.1-1/lua/http/router/matching.lua
-- Installing: /mnt/homework/.rocks/share/tarantool/rocks/http/2.0.1-1/lua/http/router/middleware.lua
-- Installing: /mnt/homework/.rocks/share/tarantool/rocks/http/2.0.1-1/lua/http/router/request.lua
-- Installing: /mnt/homework/.rocks/share/tarantool/rocks/http/2.0.1-1/lua/http/router/response.lua
-- Installing: /mnt/homework/.rocks/share/tarantool/rocks/http/2.0.1-1/lua/http/tsgi.lua
-- Installing: /mnt/homework/.rocks/share/tarantool/rocks/http/2.0.1-1/lua/http/utils.lua
-- Installing: /mnt/homework/.rocks/share/tarantool/rocks/http/2.0.1-1/lua/http/mime_types.lua
-- Installing: /mnt/homework/.rocks/share/tarantool/rocks/http/2.0.1-1/lua/http/codes.lua

**Comment by olegrok** [comment]
@cheng417723 

I hope that you've resolved your problems with Tarantool installation.

Also you can ask any questions in our English-speaking Telegram chat: https://telegram.me/tarantool
